# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async

test:
  adapter: test

prod_common: &prod_common
  adapter: postgresql
  host: <%= ENV["APP_DATABASE_HOST"] %>
  database: postgres
  username: <%= ENV["APP_DATABASE_USERNAME"] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>

production:
  primary:
    <<: *prod_common
  queue:
    <<: *prod_common
